name       : qt5-datavis3d
version    : 5.15.7
release    : 10
source     :
    - git|https://invent.kde.org/qt/qt/qtdatavis3d.git : 8e1a57efa1ba3eabbf44098ce6ede3d130c57b5d
license    : GPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt Data Visualization module
description: |
    Qt Data Visualization module
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demo : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdatavis3d.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
