name       : qt5-datavis3d
version    : 5.15.10
release    : 13
source     :
    - git|https://invent.kde.org/qt/qt/qtdatavis3d.git : d366b0aad8454355acac79eddbab445c1108b1e9
license    : GPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt Data Visualization module
description: |
    Qt Data Visualization module
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demo : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdatavis3d.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
