name       : qt5-datavis3d
version    : 5.15.3
release    : 6
source     :
    - git|https://invent.kde.org/qt/qt/qtdatavis3d.git : c085311c02dd216e5a041b90c164d55b3cf3ce92
license    : GPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt Data Visualization module
description: |
    Qt Data Visualization module
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demo : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtdatavis3d.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
