name       : qt5-datavis3d
version    : 5.13.2
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtdatavis3d-everywhere-src-5.13.2.tar.xz : ecf934c3eb07173505781734f95cfc2cf9d89e6b1b98516ac98a137797f4ef28
license    : GPL-3.0-only
component  : desktop.qt
summary    : Qt Data Visualization module
description: |
    Qt Data Visualization module
builddeps  :
    - pkgconfig(Qt5Quick)
patterns   :
    - demo : /usr/lib64/qt5/examples
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
